title: DocumentationWIki
description: Just the Docs theme for Documation using Jeykll & Github Pages
theme: just-the-docs

url: https://decodeproxy.github.io/DocumentationWIki/

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
